### ISSUE TITLE
Use the TLD in the bug report to search for duplicates

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [andreicristianpetcu/incompat#2]
Searching for duplicates using the TLD in the bug report instead of the browser's address bar would improve the speed of the webcompat.com issues triage.

![image](https://user-images.githubusercontent.com/16573771/68379065-d83dd400-0155-11ea-9917-af653286f408.png)

CC
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

**Comment by andreicristianpetcu** [comment]
@softvision-sergiulogigan Not sure what you mean. What is the actual behavior and what is the expected one?
Also, I'm super glad somebody actually uses this extension. 😃

**Comment by softvision-oana-arbuzov** [comment]
@andreicristianpetcu we are working on Webcompat project and we are interested in using the add-on to help us in our work with issue triage.

**Prerequisites:**
1. Incompat add-on installed.

**Steps to reproduce:**
1. Navigate to https://github.com/webcompat/web-bugs/issues/43620
2. Observe Incompat counter in the address bar.

**Expected result:**
Incompat counter displays the number of issues that are available for the URL main domain (e.g www.arstation.com - 2 open issues), without having to access the site from the provided URL.

**Actual result:**
Incompat counter displays the number of issues that are available for the address bar URL (e.g github.com - 3 open issues).

![image](https://user-images.githubusercontent.com/12184325/68399855-b8bba100-017f-11ea-8790-2e92cda18547.png)

**Comment by andreicristianpetcu** [comment]
That's actually a great idea! Will look into this! @softvision-sergiulogigan

**Comment by softvision-sergiulogigan** [comment]
Thanks @softvision-oana-arbuzov for clarifying this!

Also, @andreicristianpetcu, this would help us A LOT in the triage work for webcompat!

I'm aware that this request is not compatible with the add-on's original intended use

`If you want to see web compatibility bugs on sites you build or use, just install this extension and it will pull data from webcompat.com and make it visible to you in the URL bar after pages load.`

so I'm proposing an "Incompat - Triager's companion" sort of version. What I'm saying is basically a different project, based on the original "Incompat", custom made for people who triage bugs for webcompat (like us).

**Comment by andreicristianpetcu** [comment]
@softvision-sergiulogigan this feature sounds good. I actually want to implement it!

**Comment by andreicristianpetcu** [comment]
I did the change. Hope you like it @softvision-oana-arbuzov @softvision-sergiulogigan 
Make sure you have v1.1.0

**Comment by softvision-sergiulogigan** [comment]
Thanks! This looks awesome!
We'll try it for a few days and come back with feedback.

I've noticed though that the Chrome version did not got bumped up yet.

**Comment by andreicristianpetcu** [comment]
I uploaded it in CWS. It should take a bit. FF is v1.1.1 but Chrome should be v1.1.0. That is expected. I made a tiny tiny fix for FF. @softvision-sergiulogigan

**Comment by andreicristianpetcu** [comment]
@softvision-sergiulogigan Chrome version is stuck in pending approval whatever that means.

**Comment by andreicristianpetcu** [comment]
![image](https://user-images.githubusercontent.com/922368/68709055-92da3600-059d-11ea-8b38-9f3951f7b512.png)
