### ISSUE TITLE
Incompat counter should display total number of issues on a domain excluding "Needstriage" milestone

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [andreicristianpetcu/incompat#3]
**Prerequisites:**
1. Incompat add-on installed.

**Steps to reproduce:**
1. Navigate to https://www.artstation.com/artwork/9aLBR
2. Observe Incompat counter in the address bar.

**Expected result:**
Incompat counter displays total number of issues, excluding the ones from "Needstriage" milestone, that are available for the URL.
(e.g "There are X number of issues on www.arstation.com").

**Actual result:**
Incompat counter displays the number of issues that are available for the URL.
(e.g "There are 2 open issues on www.arstation.com").

**Note:**
Needstriage query: Filter: is:issue is:open in:title artstation.com OR in:title www.artstation.com OR in:title m.artstation.com OR in:title mobile.artstation.com OR in:title apps.artstation.com OR in:title free.artstation.com milestone:needstriage

https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+artstation.com+OR+in%3Atitle+www.artstation.com+OR+in%3Atitle+m.artstation.com+OR+in%3Atitle+mobile.artstation.com+OR+in%3Atitle+apps.artstation.com+OR+in%3Atitle+free.artstation.com+milestone%3Aneedstriage

The rest of the issues query: Filter: is:issue is:open in:title artstation.com OR in:title www.artstation.com OR in:title m.artstation.com OR in:title mobile.artstation.com OR in:title apps.artstation.com OR in:title free.artstation.com -milestone:needstriage

https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+in%3Atitle+artstation.com+OR+in%3Atitle+www.artstation.com+OR+in%3Atitle+m.artstation.com+OR+in%3Atitle+mobile.artstation.com+OR+in%3Atitle+apps.artstation.com+OR+in%3Atitle+free.artstation.com+-milestone%3Aneedstriage+

**Comment by andreicristianpetcu** [comment]
Why would you want to exclude needstriage?

The purpose of this extension was to make it easy for me and others to track issues on rarely used sites. For example if I see any bug on homebank.ro in any status, I would like to subscribe to it. Maybe I can triage or maybe I can contact somebody in ING to fix it.

Ignoring issues based on status is contradicting with the initial goal. Maybe I don't understand the issue you are trying to solve.

I was thinking to hide issues either manually or after the first page visit on github. This would allow me to see the issue for homebank, open github issue, subscribe on github, then hide it from the list. After another homebank visit, I will either see 0 or new issues created.

Will this sort of manual ignore per issue solve your problem?

**Comment by andreicristianpetcu** [comment]
The UI for the manual ignore can be a right click menu.

**Comment by softvision-oana-arbuzov** [comment]
Our scope is to find duplicates easy on a domain and the counter is an indicator that there are issues on it or not on it. 
After discussing with the team, we don't need to ignore Needstriage, since we could rapidly investigate all the issues from that domain (usually we get the same issue multiple times).

I will close this in favor of the previous issue with the TLD and continue discussion there. 
Thanks.

**Comment by andreicristianpetcu** [comment]
@softvision-oana-arbuzov if you are interested, I can still take a loot at ignoring milestones or labels.
I was thinking that I can make an options page where you can configure such things. If it's useful for you we can do something about it.
